//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lfin
{
    using System;
    using System.Collections.Generic;
    
    public partial class categories
    {
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
    }
}
